spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://101.101.209.147:3306/test?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
server:
  port: 8081
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
server:
  port: 8081
---